# Site settings
title: "Chinmay Awale"
email: chinubeta0710@gmail.com
description: "Casual blog of an Explorer"
baseurl: ""
url: ""
title_description: "Nothing much up to this point"
title_image: "https://graph.facebook.com/v2.9/100001240071614/picture?type=large"
google_analytics: 
disqus_account: https://disqus.com/by/chinmayawale/
github_repository: 
addthis_id: 
post_limit: 5

# Social usernames/URLs
twitter_username: 
github_username: Owl-A
instagram_username: 
reddit_username: 
linkedin_link: 
google_plus_link: 
stackoverflow_link: 
xing_link:
facebook_link: https://www.facebook.com/chinmay.awale

# Footer
footer_left: "Made with <i class=\"fa fa-heart\"></i> by <a href=\"https://twitter.com/_JacobTomlinson\">Jacob Tomlinson</a>"
footer_right: "&lt;/&gt; on <a href=\"https://github.com/jacobtomlinson/carte-noire\">Github</a> &nbsp;<i class=\"fa fa-github-alt\"></i>"

# Build settings
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge

permalink: pretty
exclude: [vendor]
