# Site settings
title: "Chinmay Awale"
email: chinubeta0710@gmail.com
description: "Casual blog of an Explorer"
baseurl: ""
url: "Owl-A.github.io"
title_image: "/images/me.jpeg"
google_analytics: 
disqus_account: owl-a 
github_repository: 
addthis_id: 
post_limit: 5

#description typing
title_description: "your average <br/> next door college graduate <br/> who fancies himself as"
dynamic-typing: True
loop: True
loop-count: False # Set False for infinite loop, or set any number for finite loop.
type-speed: 10
start-delay: 200
delete-delay: 5000
lines: # You can add HTML Tags in the Text
  - text: " a Security Expert"
  - text: " a Philosopher"
  - text: " an Innovator"
  - text: " a Casual Gamer"
  - text: " a Software Developer"
  
# Social usernames/URLs
twitter_username: Owl_A_
github_username: Owl-A
instagram_username: common.cryptid 
reddit_username: 
linkedin_link: 
google_plus_link: 
stackoverflow_link: 
xing_link:
facebook_link: https://www.facebook.com/chinmay.awale

# Footer
footer_left: "Made with <i class=\"fa fa-heart\"></i> by <a href=\"https://twitter.com/_JacobTomlinson\">Jacob Tomlinson</a>"
footer_right: "&lt;/&gt; on <a href=\"https://github.com/jacobtomlinson/carte-noire\">Github</a> &nbsp;<i class=\"fa fa-github-alt\"></i>"

# Build settings
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge

permalink: pretty
exclude: [vendor]
